name: Actions workflow

on:
# push:
# pull_request:
#  types: [opened,closed,reopened,assigned,]
  schedule:
    - cron: "0/5 * * * *"   
    - cron: "0/6 * * * *"
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
     - name: list files 
       run: | 
         pwd
         ls -a 
     - name: checkout 
       uses: actions/checkout@v1
     - name: list of file checkout 
       run: |
        pwd
        ls -a
     - name: Simple Java script
       id: greet 
       uses: actions/hello-world-javascript-action@v1
       with: 
        who-to-greet: Anand
     - name: Log Greeting time
       run: echo "${{steps.greet.outputs.time}}"




