name: shell commands

on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run : echo "Hello Anand"
      - name: multiline script
        run: | 
          node -v
          npm -v
      - name: python commands
        run : |
          import platform
          print(platform.processor())
        shell: python
  run-widnows-commads:
   runs-on: windows-latest
   needs: ["run-shell-commands"]
   steps:
     - name: Directory Powershell
       run : Get-Location
     - name: Directory Bash
       run : pwd
       shell: bash     



